"""initial schema

Revision ID: 093cae67bbb3
Revises: 
Create Date: 2026-08-18 18:50:20.633001
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '093cae67bbb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('careers_url', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('size_hint', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('preference_boost', sa.Float(), nullable=False),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('discovered_via', sa.String(length=80), nullable=True),
    sa.Column('jobs_seen_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_is_blacklisted'), ['is_blacklisted'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_is_monitored'), ['is_monitored'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_is_preferred'), ['is_preferred'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_slug'), ['slug'], unique=True)

    op.create_table('dedup_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('left_key', sa.String(length=300), nullable=False),
    sa.Column('right_key', sa.String(length=300), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dedup_decisions'))
    )
    with op.batch_alter_table('dedup_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dedup_decisions_run_id'), ['run_id'], unique=False)

    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_credentials', sa.Boolean(), nullable=False),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_jobs_returned', sa.Integer(), nullable=False),
    sa.Column('total_unique_contributed', sa.Integer(), nullable=False),
    sa.Column('total_relevant_contributed', sa.Integer(), nullable=False),
    sa.Column('total_strong_matches', sa.Integer(), nullable=False),
    sa.Column('avg_duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_job_sources_name'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('job_count', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('queries_generated', sa.Integer(), nullable=False),
    sa.Column('sources_attempted', sa.Integer(), nullable=False),
    sa.Column('sources_successful', sa.Integer(), nullable=False),
    sa.Column('sources_failed', sa.Integer(), nullable=False),
    sa.Column('sources_unconfigured', sa.Integer(), nullable=False),
    sa.Column('raw_jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_normalized', sa.Integer(), nullable=False),
    sa.Column('duplicates_removed', sa.Integer(), nullable=False),
    sa.Column('unique_jobs', sa.Integer(), nullable=False),
    sa.Column('relevant_jobs', sa.Integer(), nullable=False),
    sa.Column('high_priority_jobs', sa.Integer(), nullable=False),
    sa.Column('new_jobs', sa.Integer(), nullable=False),
    sa.Column('updated_jobs', sa.Integer(), nullable=False),
    sa.Column('reposted_jobs', sa.Integer(), nullable=False),
    sa.Column('expired_jobs', sa.Integer(), nullable=False),
    sa.Column('companies_discovered', sa.Integer(), nullable=False),
    sa.Column('ats_boards_discovered', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('notifications_sent', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_runs'))
    )
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_runs_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('ats_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('board_token', sa.String(length=200), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('discovered_via', sa.String(length=80), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('jobs_last_crawl', sa.Integer(), nullable=False),
    sa.Column('relevant_jobs_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ats_boards_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ats_boards'))
    )
    with op.batch_alter_table('ats_boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ats_boards_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_ats_boards_crawl', ['enabled', 'last_crawled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ats_boards_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ats_boards_provider'), ['provider'], unique=False)
        batch_op.create_index('ix_ats_boards_provider_token', ['provider', 'board_token'], unique=True)

    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=300), nullable=True),
    sa.Column('degree', sa.String(length=150), nullable=True),
    sa.Column('major', sa.String(length=200), nullable=True),
    sa.Column('minor', sa.String(length=200), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('graduation_month', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('technical_skills', sa.JSON(), nullable=False),
    sa.Column('programming_languages', sa.JSON(), nullable=False),
    sa.Column('hardware_skills', sa.JSON(), nullable=False),
    sa.Column('software_skills', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('research_experience', sa.Text(), nullable=True),
    sa.Column('previous_internships', sa.JSON(), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('publications', sa.JSON(), nullable=False),
    sa.Column('coursework', sa.JSON(), nullable=False),
    sa.Column('preferred_industries', sa.JSON(), nullable=False),
    sa.Column('work_authorization', sa.String(length=120), nullable=True),
    sa.Column('requires_sponsorship', sa.Boolean(), nullable=True),
    sa.Column('security_clearance', sa.String(length=120), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=False),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_candidate_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_candidate_profiles_user_id'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_job_id', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('ats_identity', sa.String(length=300), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_core', sa.String(length=500), nullable=False),
    sa.Column('location_raw', sa.String(length=400), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('remote_status', sa.String(length=20), nullable=False),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('preferred_qualifications', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_period', sa.String(length=20), nullable=True),
    sa.Column('salary_raw', sa.String(length=300), nullable=True),
    sa.Column('application_url', sa.String(length=1000), nullable=False),
    sa.Column('posting_url', sa.String(length=1000), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('date_discovered', sa.DateTime(), nullable=True),
    sa.Column('date_updated_source', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('deadline_is_explicit', sa.Boolean(), nullable=False),
    sa.Column('sponsorship', sa.String(length=40), nullable=False),
    sa.Column('sponsorship_evidence', sa.Text(), nullable=True),
    sa.Column('experience_required_years', sa.Float(), nullable=True),
    sa.Column('degree_requirements', sa.JSON(), nullable=False),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('requisition_id', sa.String(length=120), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('match_reasons', sa.JSON(), nullable=False),
    sa.Column('missing_requirements', sa.JSON(), nullable=False),
    sa.Column('concerns', sa.JSON(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('llm_assessment', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('freshness', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('times_reposted', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('first_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_jobs_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_active_posted', ['is_active', 'date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_ats_identity'), ['ats_identity'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_canonical_job_id'), ['canonical_job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_date_discovered'), ['date_discovered'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_date_posted'), ['date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_deadline'), ['deadline'], unique=False)
        batch_op.create_index('ix_jobs_fingerprint', ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_first_run_id'), ['first_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_freshness'), ['freshness'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_notified'), ['notified'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_relevance_score'), ['relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_requisition_id'), ['requisition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_score', ['status', 'relevance_score'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resumes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_table('search_run_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jobs_returned', sa.Integer(), nullable=False),
    sa.Column('unique_contributed', sa.Integer(), nullable=False),
    sa.Column('relevant_contributed', sa.Integer(), nullable=False),
    sa.Column('queries_run', sa.Integer(), nullable=False),
    sa.Column('sub_targets_attempted', sa.Integer(), nullable=False),
    sa.Column('sub_targets_successful', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['search_runs.id'], name=op.f('fk_search_run_sources_run_id_search_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_run_sources'))
    )
    with op.batch_alter_table('search_run_sources', schema=None) as batch_op:
        batch_op.create_index('ix_run_source', ['run_id', 'source'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_preferences_user_id'))
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('date_saved', sa.DateTime(), nullable=True),
    sa.Column('date_applied', sa.DateTime(), nullable=True),
    sa.Column('date_assessment', sa.DateTime(), nullable=True),
    sa.Column('date_interview', sa.DateTime(), nullable=True),
    sa.Column('date_offer', sa.DateTime(), nullable=True),
    sa.Column('date_rejected', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('resume_version', sa.String(length=200), nullable=True),
    sa.Column('cover_letter_version', sa.String(length=200), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('referral', sa.String(length=300), nullable=True),
    sa.Column('score_at_apply', sa.Float(), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_applications_resume_id_resumes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('job_id', name='uq_application_job')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_date_applied'), ['date_applied'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_job_events_job_created', ['job_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_run_id'), ['run_id'], unique=False)

    op.create_table('job_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('source_job_id', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True),
    sa.Column('canonical_url_hash', sa.String(length=64), nullable=True),
    sa.Column('apply_url', sa.String(length=1000), nullable=True),
    sa.Column('ats_identity', sa.String(length=300), nullable=True),
    sa.Column('title_raw', sa.String(length=500), nullable=True),
    sa.Column('company_raw', sa.String(length=300), nullable=True),
    sa.Column('location_raw', sa.String(length=400), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('merge_method', sa.String(length=40), nullable=True),
    sa.Column('merge_confidence', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_listings_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_listings')),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_listing_source_id')
    )
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_listings_ats_identity'), ['ats_identity'], unique=False)
        batch_op.create_index('ix_job_listings_job', ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_listings_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_listings_source'), ['source'], unique=False)
        batch_op.create_index('ix_job_listings_url_hash', ['canonical_url_hash'], unique=False)

    op.create_table('notification_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_notification_items_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_items_notification_id_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_items'))
    )
    with op.batch_alter_table('notification_items', schema=None) as batch_op:
        batch_op.create_index('ix_notification_items_job', ['job_id'], unique=False)

    op.create_table('application_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_notes_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_notes'))
    )
    with op.batch_alter_table('application_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_notes_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_notes_application_id'))

    op.drop_table('application_notes')
    with op.batch_alter_table('notification_items', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_items_job')

    op.drop_table('notification_items')
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_index('ix_job_listings_url_hash')
        batch_op.drop_index(batch_op.f('ix_job_listings_source'))
        batch_op.drop_index(batch_op.f('ix_job_listings_last_seen_at'))
        batch_op.drop_index('ix_job_listings_job')
        batch_op.drop_index(batch_op.f('ix_job_listings_ats_identity'))

    op.drop_table('job_listings')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_run_id'))
        batch_op.drop_index('ix_job_events_job_created')
        batch_op.drop_index(batch_op.f('ix_job_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_job_events_created_at'))

    op.drop_table('job_events')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_date_applied'))

    op.drop_table('applications')
    op.drop_table('user_preferences')
    with op.batch_alter_table('search_run_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_run_source')

    op.drop_table('search_run_sources')
    op.drop_table('resumes')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_score')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_requisition_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_relevance_score'))
        batch_op.drop_index(batch_op.f('ix_jobs_priority'))
        batch_op.drop_index(batch_op.f('ix_jobs_notified'))
        batch_op.drop_index(batch_op.f('ix_jobs_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_is_active'))
        batch_op.drop_index(batch_op.f('ix_jobs_freshness'))
        batch_op.drop_index(batch_op.f('ix_jobs_first_run_id'))
        batch_op.drop_index('ix_jobs_fingerprint')
        batch_op.drop_index(batch_op.f('ix_jobs_deadline'))
        batch_op.drop_index(batch_op.f('ix_jobs_date_posted'))
        batch_op.drop_index(batch_op.f('ix_jobs_date_discovered'))
        batch_op.drop_index(batch_op.f('ix_jobs_company_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_canonical_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_ats_identity'))
        batch_op.drop_index('ix_jobs_active_posted')

    op.drop_table('jobs')
    op.drop_table('candidate_profiles')
    with op.batch_alter_table('ats_boards', schema=None) as batch_op:
        batch_op.drop_index('ix_ats_boards_provider_token')
        batch_op.drop_index(batch_op.f('ix_ats_boards_provider'))
        batch_op.drop_index(batch_op.f('ix_ats_boards_enabled'))
        batch_op.drop_index('ix_ats_boards_crawl')
        batch_op.drop_index(batch_op.f('ix_ats_boards_company_id'))

    op.drop_table('ats_boards')
    op.drop_table('users')
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_runs_status'))
        batch_op.drop_index(batch_op.f('ix_search_runs_started_at'))

    op.drop_table('search_runs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_run_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    op.drop_table('job_sources')
    with op.batch_alter_table('dedup_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dedup_decisions_run_id'))

    op.drop_table('dedup_decisions')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_slug'))
        batch_op.drop_index(batch_op.f('ix_companies_is_preferred'))
        batch_op.drop_index(batch_op.f('ix_companies_is_monitored'))
        batch_op.drop_index(batch_op.f('ix_companies_is_blacklisted'))

    op.drop_table('companies')
    # ### end Alembic commands ###
